const hpMemList = [
    {map:"Echo Ridge",world:"Real World",location:"Story Progress - HELP quest",item:"HP Memory 10"},
    {map:"Echo Ridge",world:"Real World",location:"Examine thermostat (Zack's Room)",item:"HP Memory 20"},
    {map:"Echo Ridge", world:"Real World", location:"Ken Suther's HELP (BIG WAVE)", item: "HP Memory 10"},
    {map:"Echo Ridge", world:"Wave World", location:"Geo's Room EM-Road BMW", item: "HP Memory 10"},
    {map:"Echo Ridge", world:"Wave World", location:"Big Wave EM-Road BMW", item: "HP Memory 20"},
    {map:"Echo Ridge", world:"Wave World", location:"Pitcher Comp BMW", item: "HP Memory 10"},
    {map:"Echo Ridge", world:"Wave World", location:"Video Game Comp BMW (Bud's Room)", item: "HP Memory 10"},
    {map:"Echo Ridge", world:"Wave World", location:"Truck Comp 2", item: "HP Memory 20"},
    {map:"Echo Ridge", world:"(SHOP)Wave World", location:"Echo Ridge EM-Rd(1000ƶ)", item: "HP Memory 20"},
    {map:"Echo Ridge", world:"(SHOP)Wave World", location:"Echo Ridge EM-Rd(3000ƶ)", item: "HP Memory 20"},
    {map:"Echo Ridge", world:"(SHOP)Real World", location:"BIG WAVE(4000ƶ)", item: "HP Memory 20"},
    {map:"Echo Ridge", world:"(SHOP)Real World", location:"BIG WAVE(8000ƶ)", item: "HP Memory 20"},
    {map:"Echo Ridge", world:"(SHOP)Real World", location:"BIG WAVE(16000ƶ)", item: "HP Memory 20"},

    {map:"AMAKEN", world:"Real World", location:"Examine Jupiter (SpaceSim)", item: "HP Memory 10"},
    {map:"AMAKEN", world:"Real World", location:"Examine rightmost telescope", item: "HP Memory 10"},
    {map:"AMAKEN", world:"Real World", location:"Pat Sprig's HELP (Boreal's Lab)", item: "HP Memory 10"},
    {map:"AMAKEN", world:"Wave World", location:"AMAKEN Grounds EM-Road BMW", item: "HP Memory 20"},
    {map:"AMAKEN", world:"Wave World", location:"Rocket Comp BMW", item: "HP Memory 10"},
    {map:"AMAKEN", world:"Wave World", location:"Space Colony Comp", item: "HP Memory 20"},
    {map:"AMAKEN", world:"Wave World", location:"SpaceSim Comp 1", item: "HP Memory 20"},
    {map:"AMAKEN", world:"(SHOP)Wave World", location:"AMAKEN Grounds EM-Rd(3000ƶ)", item: "HP Memory 20"},
    {map:"AMAKEN", world:"(SHOP)Wave World", location:"AMAKEN Grounds EM-Rd(5000ƶ)", item: "HP Memory 20"},

    {map:"Echo Ridge Elementary", world:"Real World", location:"Examine teacher's desk (Class 1-A)", item: "HP Memory 10"},
    {map:"Echo Ridge Elementary", world:"Real World", location:"Examine cameras (Studio)", item: "HP Memory 20"},
    {map:"Echo Ridge Elementary", world:"Real World", location:"Mitch Shepar's HELP (Studio)", item: "HP Memory 10"},
    {map:"Echo Ridge Elementary", world:"Wave World", location:"Class 5-A EM-Road BMW", item: "HP Memory 10"},
    {map:"Echo Ridge Elementary", world:"Wave World", location:"Principal Comp BMW", item: "HP Memory 10"},
    {map:"Echo Ridge Elementary", world:"Wave World", location:"5-B Comp BMW", item: "HP Memory 10"},
    {map:"Echo Ridge Elementary", world:"Wave World", location:"School Comp 3 BMW", item: "HP Memory 20"},

    {map:"Time Square", world:"Real World", location:"Examine blue statue next to Rover dog statue (Time Square)", item: "HP Memory 10"},
    {map:"Time Square", world:"Real World", location:"Bob Copper's HELP (Outside)", item: "HP Memory 20"},
    {map:"Time Square", world:"Real World", location:"Vaughn Platz's HELP", item: "HP Memory 10"},
    {map:"Time Square", world:"Real World", location:`Donna Query's HELP (Outside)<br>
        (Must do Triv Query’s HELP first)`, item: "HP Memory 10"},
    {map:"Time Square", world:"Wave World", location:"Time Square EM-Road BMW", item: "HP Memory 20"},
    {map:"Time Square", world:"Wave World", location:"Mowai Comp BMW", item: "HP Memory 10"},
    {map:"Time Square", world:"Wave World", location:"Cake Shop Comp BMW", item: "HP Memory 10"},
    {map:"Time Square", world:"Wave World", location:"Robo Snake Comp 2 BMW", item: "HP Memory 20"},

    {map:"Dream Island", world:"Real World", location:"Examine garbage trucks (Dream Island)", item: "HP Memory 10"},
    {map:"Dream Island", world:"Real World", location:"Examine wooden table (Dream Park)", item: "HP Memory 10"},
    {map:"Dream Island", world:"Real World", location:"Examine tires stacked next to barrels (Scrapyard 1)", item: "HP Memory 20"},
    {map:"Dream Island", world:"Real World", location:`Roy Query's HELP (Dream Island)<br>
        (Must do Donna Query and Triv Query's HELP first)`, item: "HP Memory 20"},
    {map:"Dream Island", world:"Real World", location:"Selah Agane's HELP (Dream Island)", item: "HP Memory 10"},
    {map:"Dream Island", world:"Real World", location:"Mead Greene's HELP (Dream Park)", item: "HP Memory 10"},
    {map:"Dream Island", world:"Real World", location:"John Forman's HELP (City Dump)", item: "HP Memory 10"},
    {map:"Dream Island", world:"Real World", location:"Aaron Boreal's HELP (Island Underground)", item: "HP Memory 20"},
    {map:"Dream Island", world:"Wave World", location:"Scrapyard 2 EM-Road BMW", item: "HP Memory 20"},
    {map:"Dream Island", world:"Wave World", location:"Pirate Ship Comp BMW (Dream Park)", item: "HP Memory 10"},
    {map:"Dream Island", world:"(SHOP)Wave World", location:"City Dump EM-Rd(6000ƶ)", item: "HP Memory 20"},
    {map:"Dream Island", world:"(SHOP)Wave World", location:"City Dump EM-Rd(10000ƶ)", item: "HP Memory 20"},
    {map:"Dream Island", world:"(SHOP)Wave World", location:"City Dump EM-Rd(20000ƶ)", item: "HP Memory 20"},

    {map:"Space Station", world:"Real World", location:"Examine the oxygen tanks (Service Module)", item: "HP Memory 20"},
    {map:"Space Station", world:"Wave World", location:"Service Module EM-Road PMW", item: "HP Memory 20"},
    {map:"Space Station", world:"Wave World", location:"Power Module EM-Road BMW", item: "HP Memory 10"},
    {map:"Space Station", world:"Wave World", location:"AC Module Comp BMW", item: "HP Memory 10"},
    {map:"Space Station", world:"Wave World", location:"Test Monitor Comp BMW (Living Module)", item: "HP Memory 10"},
    {map:"Space Station", world:"Wave World", location:"Living Module Comp BMW (Comp accessed via invisible path / Lonely Heart location)", item: "HP Memory 10"},
    {map:"Space Station", world:"Wave World", location:"Station Comp 4 BMW", item: "HP Memory 20"},


    {map:"Deep Space", world:"Wave World", location:"Deep Space 3 EM-Road BMW (through Lonely Heart door)", item: "HP Memory 20"},
    {map:"Deep Space", world:"(SHOP)Wave World", location:"DeepSpace 2 EM-Road(10000ƶ)", item: "HP Memory 20"},
    {map:"Deep Space", world:"(SHOP)Wave World", location:"DeepSpace 2 EM-Road(30000ƶ)", item: "HP Memory 20"},
]
